@startuml
!include ../../components/action.puml
start
$ruleway_action( \
  $id="РТЕ-02", \
  $name="Проверить заявку на изменение структуры проекта и связанных сущностей трекера", \
  $responsible="Ответственный за сопровождение процессов", \
  $result="Заключение о полноте и корректности заявки с перечнем замечаний и рекомендациями по доработке" + %newline() + "[[materials/review_template.html Шаблон заключения]]", \
  $instruction='1. Проверить "цель"; сохранить замечания;' + %newline() + "2. Сверить комплект документов." + %newline() + "3. Проверить каждую затронутую сущность и связь с действующим порядком работы.", \
  $sla="До конца следующего рабочего дня после получения полного комплекта документов", \
  $subregulation="[[review_regulation.svg Подрегламент: проверка заявки]]" \
)
$ruleway_action("РТЕ-03", "Оформить итог", "Согласующий", \
  "[[materials/review_template.html Заключение по шаблону]]", \
  "Заполнить заключение связным текстом; передать его инициатору.")
stop
@enduml
