@startuml
!include ../../components/action.puml
|Автор|
start
repeat
  $ruleway_action("РПР-01", "Исправить документ", "Автор", "Новая редакция документа")
  |Проверяющий|
  $ruleway_action("РПР-02", "Проверить изменения", "Проверяющий", "Решение о готовности")
repeat while (Нужна доработка?) is (да) not (нет)
fork
  $ruleway_action("РПР-03", "Сохранить документ", "Проверяющий", "Редакция сохранена")
fork again
  $ruleway_action("РПР-04", "Уведомить участников", "Проверяющий", "Участники уведомлены о новой редакции")
end fork
|Автор|
$ruleway_action("РПР-05", "Завершить работу", "Автор", "Документ принят")
stop
@enduml
