@startuml
' Макет Б: карточка с разделами. Не реализация компонента.
!include action_design_content.iuml
caption Б · Карточка с разделами
start
:<color:#087F74><b>$ruleway_design_id</b></color>
<size:16><b>$ruleway_design_name</b></size>
----
<b>Ответственный</b>
$ruleway_design_role
<b>Срок / SLA</b>
$ruleway_design_sla
----
<color:#087F74><b>Результат</b></color>
$ruleway_design_result
$ruleway_design_template
----
<color:#087F74><b>Инструкция / чек-лист</b></color>
$ruleway_design_instruction_1
$ruleway_design_instruction_2
$ruleway_design_instruction_3
!ifdef ruleway_design_long
$ruleway_design_instruction_4
!endif
!ifndef ruleway_design_no_subreg
----
$ruleway_design_child
!endif
;
stop
@enduml
